### PR TITLE
fix: changing the theme through short cut menu.

### LINKED ISSUE #204: Incorrect Color Selection for Text and Background in Themes
I am experiencing an issue with the JetBrains plugin where it incorrectly selects colors for both text and background when switching between themes. The plugin sometimes identifies the correct colors, but at other times it fails to do so, leading to poor visibility and readability. 
## Steps to Reproduce:
- Install the plugin in JetBrains IDE.
- Switch between different themes (e.g., Light, Dark, Custom).
- Observe the color selection for both text and background in the editor.
## Expected Behavior:
The plugin should consistently select appropriate colors for both text and background that match the selected theme, ensuring good visibility and readability. Actual Behavior:
The plugin sometimes selects incorrect colors for text and background, which can lead to text being unreadable against the background. Environment:
- JetBrains IDE version: [2024.3.1.1]
- Plugin version: [5.2.2]
- Operating System: [mac os 15.1.1]
## Additional Information:
https://github.com/user-attachments/assets/16d0684a-d3ac-4f7b-b58b-70adca2d84ef

### PR DESCRIPTION
**Pull request by MarcMcIntosh**
Fixes #204 

To recreate the issues change the theme using the short cut menu  **^\`** select `theme` and click on a theme.

Ticket: https://refact.fibery.io/Software_Development/UI-chat-js-133#Task/JB-theme-changes-544

### CODE REVIEW

File: src/main/kotlin/com/smallcloud/refactai/panes/sharedchat/SharedChatPane.kt [hunk 1]
```diff
@@ -228,8 +226,16 @@ class SharedChatPane(val project: Project) : JPanel(), Disposable {
         val ef = EditorFactory.getInstance()
         ef.eventMulticaster.addSelectionListener(selectionListener, this)
 
-        ApplicationManager.getApplication().messageBus.connect(this).subscribe(LafManagerListener.TOPIC, uiChangeListener)
-
+//        ApplicationManager.getApplication().messageBus.connect(this).subscribe(UISettingsListener.TOPIC,
```
Comment (reymondzzzz) [inline src/main/kotlin/com/smallcloud/refactai/panes/sharedchat/SharedChatPane.kt:229]: delete comments

File: src/main/kotlin/com/smallcloud/refactai/panes/sharedchat/browser/ChatWebView.kt [hunk 2]
```diff
@@ -299,7 +302,7 @@ class ChatWebView(val editor: Editor, val messageHandler: (event: Events.FromCha
     fun postMessage(message: Events.ToChat<*>?) {
         if (message != null) {
             val json = Events.stringify(message)
-            // println("post message json: $json")
+            println("post message json: $json")
```
Comment (reymondzzzz) [inline src/main/kotlin/com/smallcloud/refactai/panes/sharedchat/browser/ChatWebView.kt:305]: use logger instead println

**Review by reymondzzzz — APPROVED** [review]
